### ISSUE TITLE
Remote ajax settings don't appear to work

### ISSUE THREAD

**Issue by danstanhope** [twitter/typeahead.js#1136]
Hey Guys,

I'm passing cache : false and the cache doesn't appear to change, only one request ever gets made. Might not be a bug and I could just be missing something. Great plug-in and thanks!

```
        var topics = new Bloodhound({
                datumTokenizer: function (d){

                },
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                remote: {
                  url: "url",
                  ajax : {
                      type: "POST",
                      cache : false,
                      data: { 
                        "profile"   : 'user',                               
                        search: function() {
                          return $('#keywords').val() 
                        }                              
                      }
                  },
                  filter: function(list) {
                    return $.map(list.data.topics, function(topic) { return { value: topic.topics }; });
                  }                        
                }
        });
```

**Comment by jharding** [comment]
There's a small internal cache to bloodhound to deal with recent queries. It caches the 10 latest queries with the goal being that a network request doesn't get made due to the user hitting backspace a few times.

You can disable this cache by passing `cache: false` in the remote option hash. This option is currently undocumented, but I'll try and get it documented in the coming days.
