### ISSUE TITLE
Suggestions don't work properly when term is surrounded by underscores "()" or brackets "[]"

### ISSUE THREAD

**Issue by AnderUstarroz** [twitter/typeahead.js#1173]
I've realized that the suggestions are not displayed correctly when looking for words that are contained between underscores or brackets. For example having the following data collection:
```
    [{ value: 1, text: 'Extraordinary (great)'},
     {value: 2, text: '(great) mountain'},
     {value: 2, text: 'My car is [great]'}]
```
If you search for the term "great", it won't work.
Please have a look at this [jsfiddle example](https://jsfiddle.net/AnderUstarroz/dph5bkg3/) for a demonstration.

**Comment by edwardgronroos** [comment]
This as expected behaviour when using the bloodhound whitespace tokenizer.
It will just split words based on whitespace and not on special chars and thus you need to search for "(" or "[" to make a match.

Bloodhound looks for matches in the beginning of each token. So in the same way you don't get any match in your example by typing "ive" or "oun" that is partial matches on words in your dataset.

To solve your problem you need to make sure your dataset is normalized beforehand, something like this and update what field bloodhound is using for tokenizing:
```
 [
  { value: 1, text: 'Extraordinary (great)', norm: 'Extraordinary great'},
  {value: 2, text: '(great) mountain', norm: 'great mountain'},
  {value: 2, text: 'My car is [great]', norm: 'My car is great'}
]
```

... or perhaps it would suffice to just use typeahead without bloodhound like this [jsfiddle example](https://jsfiddle.net/9j816rm1/)

**Comment by AnderUstarroz** [comment]
Sorry @edwardgronroos, I guess I didn't know enough about bloodhound.
Thanks for your throughout answer ;)
