### ISSUE TITLE
Color of the .tt-suggestion.tt-cursor can't be changed

### ISSUE THREAD

**Issue by 8Sarit** [twitter/typeahead.js#1174]
I have to change the color of the font of the .tt-suggestion.tt-cursor and remove it's background.

The following css doesn't work
.tt-suggestion.tt-cursor {
	color: #009bc6;
    /*background-color: #0097cf;*/  ---->remove it
}

**Comment by ericbonintrafic** [comment]
I have tried your CSS and it colors the font in blue (with your code #009bc6) and the background in a very similar blue (with your code #0097cf) on my end. If you want to remove the background color, simply use ```background-color: none;```. If this CSS really isn't working for you, you probably need to make your rule more precise (other rules may be applying style on your typeahead font and background color). Instead of just using ```.tt-suggestion.tt-cursor```, try adding more selectors before this rule. For example, if your typeahead is placed inside a div with the ```search``` class, you can try this rule : 
```div.search .tt-suggestion.tt-cursor```
This will give priority to your rule and will overwrite what other rules might have applied on your typeahead suggestions.

**Comment by dessalines** [comment]
This is still an issue for me
