### ISSUE TITLE
Selecting id's, displaying values

### ISSUE THREAD

**Issue by hannesfostie** [twitter/typeahead.js#193]
I've just implemented typeahead to serve as a kind of autocomplete select tag, fetching the names, companies and emails of a bunch of users. However upon selecting one of them, it sets the value of the text field to the id of the object in question, while I want to display the name.

In other words, I'd like to mimic something like `<option value="1">John Doe</option>` where I would submit the 1 value while never having to display it. And I prefer not having to do an additional query to find a person based on their name (which may not even be unique all the time).

I hope that makes sense.
Hannes

**Comment by Erwane** [comment]
Sorry but i found no way to do somethng like that ...

Typing : erw
Display : Erwane Breton (erwane@phea.fr)   (the title key in json return)
onSelect : fill the input with "Erwane Breton" (the name key in json return)

the :select event is fired BUT the this.close() call this.input.resetInputValue() after and change the field value.

Any ideas ?

**Comment by noglance** [comment]
Looks like very old and popular issue. Is there any working solutions? There is several options: displayKey, valueKey; and it would be very useful to set independent values with this keys for key(id) and object value (something human readable) because sending form with object but not with key of this object sometimes impossible. For example you have list of cities and some of them have similar names. With the help of templates you can redefine output to make it clear. How to get id of selected object? May be I'm missing something but it is still not working form me.

**Comment by cromulus** [comment]
agreed. I'd really like to be able to specify what values are submitted in the typeahead for independent of the values displayed...

**Comment by pragmaticsc** [comment]
👍  this would be the perfect solution for "I need a select box, but there are 1000s of possible values", however this very simple feature is missing.
