### ISSUE TITLE
Could Typehead work with <div contenteditable="true"></div>?

### ISSUE THREAD

**Issue by amrnt** [twitter/typeahead.js#235]
I want to use Typehead on a div not an input!

**Comment by guncha** [comment]
For the benefit of anyone who lands here, it's actually quite simple to get Typeahead working with `contenteditable`. You need to hack jQuery to respond to #val() method for your element since it's what Typeahead uses. It can be easily achieved using `$.valHooks` as described here:

http://daffl.github.io/2011/11/28/valhooks.html

Remember to set the `type` on the element itself node since just doing an attribute is likely not going to work.

**Comment by jraack** [comment]
@jharding 

```
var original = $.fn.val;
$.fn.val = function() {
    if ($(this).is('*[contenteditable=true]')) {
        return $.fn.html.apply(this, arguments);
    };
    return original.apply(this, arguments);
};
```

use to overwrite val function and it will work with the contenteditable div.

Cheers.
Joe

**Comment by waqasy** [comment]
@jraack Thanks for sharing trick. It works except it doesn't preserve the older text in div.

**Comment by Nesvet** [comment]
Hey there, look at this:

```javascript
ourContenteditableElement.addEventListener("input", function () {
	this.value = this.innerText;
});
```
That's it. Now jQuery's `$(ourContenteditableElement).val()` returns exactly what we expect.

**Comment by kartikjain** [comment]
@jraack does this have to be added in jquery library and anything else besides this? Total noob in this aspect. 
Thanks for the help .

**Comment by Displee** [comment]
Nice hack @jraack
