### ISSUE TITLE
Remote example is broken

### ISSUE THREAD

**Issue by sergeychernyshev** [twitter/typeahead.js#637]
I noticed that remote example is broken and returns 404s for data/films/queries/xyz.json requests.

Makes it hard to understand how it's supposed to work.

**Comment by ghost** [comment]
I agree with Sergey, it's quite confusing, getting a 404 let think that something is broken in the example.
Maybe adding a note above the input, like : "Hint : type 'br', only 'braveheart' is on the prefetch, other come from remote source". Otherwise somewhere in the example, giving the link https://github.com/twitter/typeahead.js/tree/gh-pages/data/films/queries , so we could easily pick up a working suggestion to see the behavior without wondering what's wrong :-)

**Comment by sepehr** [comment]
I agree too, spent quite a long time figuring that out.
