### ISSUE TITLE
BloodHound ignoring TTL on prefetch

### ISSUE THREAD

**Issue by sinaa** [twitter/typeahead.js#641]
We are experiencing an issue with bloodhound's cache, which is not refreshed after the suggested TTL. even at the low settings below:

```
var users = new Bloodhound({
        datumTokenizer: function(d) {
            return d.tokens;
        },
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        prefetch: 'URL',
        ttl:1
    });
```

I assume this should refresh the cache after every millisecond. However, it keeps the cache even after several refreshes. There is also no trace of a request to the URL either.

**Comment by RomkaLTU** [comment]
Very nasty solution localStorage.clear(); before typeahead().
Any ideas how to just disable cashe? TTL completely not working.

**Comment by the911s** [comment]
@justinhomes and others, I know this is a little stale, but numbers like `1393469786476` are timestamps for the time at which the data will be cleared (not the amount of time they'll be saved). So, it's probably working as expected.

**Comment by rash805115** [comment]
I had the same issue, but like @romeoonisim said, first clear the local storage cache because your data is already cached from your previous code. E.g. at first I was testing without TTL. So naturally the cache was set to 1 day. Then I added the TTL of 5 seconds and expected the cache to expire after 5 seconds. Well it won't because the cache is already set to 1 day. You first need to remove the old cached data, and again run your code.

Maybe it is possible to NOT clear the cache and reinitialize bloodhound with `bloodhound.initialize(true)`. Maybe this would work too, haven't tested it, but the first approach is tested and it works.

Regards.

**Comment by andrewevans** [comment]
This is what I had to do:

1. Manually delete the local storage for that page to ensure it's not looking at old data. If Chrome, go to Chrome Developer Tools -> Application -> Clear storage -> click "Clear selected" (I swear I have to click it a few times to make it work). This deletes all site data, so only delete Local storage if you want to keep cookies etc.
2. Uncheck Chrome Developer Tools -> Network -> "Disable cache".

Docs say "Initialization entails adding the data provided by local and prefetch to the internal search index" so I believe it will check local storage before any of your settings. And if your last settings put data in there with a timestamp, then it will get it.

**Comment by micahlisonbee** [comment]
@andrewevans this solution is fine if you're the only user of the application.
