### ISSUE TITLE
Add Option to change the default CSS options

### ISSUE THREAD

**Issue by imolorhe** [twitter/typeahead.js#677]
I am currently working on a project and decided to use typahead.js in it. It works fine so far. However, there are instances where the default CSS values used don't work well for me (especially the absolute positioning). There should be a way to override these values.

**Comment by afirdousi** [comment]
I have a similar request for my situation. One a single text box, I show 3 types of suggestions. When the user selects from suggestion for the first time, a new request is made for different collection and then I show it again in type-ahead...the 3rd time type ahead appears the same way. The problem is user can also do a backspace at the 2nd or 3rd type-ahead appearance, what happens is dynamically it changes the collection to give appropriate suggestion but the position , the absolute position of suggestions remain the old one...Once the user starts typing it goes back to normal..

Any idea how to manipulate with the $position factory injected in typeahead directive.

**Comment by maggiben** [comment]
This is as bad as it gets, I had to resort to this "awful" css to get my typeahead component display the suggestion menu to the right.

``` language-css
  right: 0px !important;
  left: -100% !important;
```

> ...It originally did. There were 2 reasons why I switched to using inline styles: 1) dropped the dependency on additional CSS which made it easier to get started with typeahead.js IMO and 2) I felt the styles typeahead.js was applying were essential to the typeahead working correctly so I wanted to make sure they weren't easy to override.

Chances are you're going to write custom css to style the component to meet your design rules, so bottom line is, additional css is guaranteed to be needed.
On the other hand, while the menu container is absolutely positioned it does so relative to it's parent not the entire viewport, there is no necessity to fiddle around absolute x&y coordinates... (unless you're in a modal and the dropdown menu is appended to the `<body>` a feature that typeahead does not support btw...)
We're just talking about left, right, top and bottom positioning, just like every other dropdown menu out there... An ideal solution should allow some degree of customization either by optional arguments in the javascript or css...
