### ISSUE TITLE
10.0.*: How to select first suggestion programmatically?

### ISSUE THREAD

**Issue by ivadenis** [twitter/typeahead.js#734]
I'm using typeahead with Google Places api to pull cities. When user searches the location, he is then redirected to that location page. I will be remembering this location (either through cookie or backend) and pre-filling the typeahead field with it. Behaviour is similar that of Yelp, you type the location and when you refresh or come back you have location filed preffield...

I need to be able to set that location to a search field programmatically. How do I do that?

P.S.: right now, on 'completed' event there are some other things happening (like getting geo location of that particular location etc.), so ultimately I would need to trigger these events too.

Thanks!

**Comment by rxvcgiii** [comment]
I'm glad to see this has been added, but I don't see how to use it in the API.  Am I simply missing it?

**Comment by amfischer** [comment]
I'm also confused about how to do this. I can use `$(querySelector).typeahead('val', 'new value')` to change the contents of the input and have the proper suggestions show, but cannot understand what to call next in order to select first option.  

I've also tried manually triggering keyboard events to get the same affect, but I don't think this is possible. [MDN](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent) says manually firing keyboard events doesn't generate the default actions in a UI for security reasons
