### ISSUE TITLE
Unwanted behaviour when using .typeahead('val', myVal); - Take 2

### ISSUE THREAD

**Issue by ttimbul** [twitter/typeahead.js#800]
Issue #646 suggested that the suggestion drop down opening was 'unwanted behaviour'.

However, I have a different use case which actually _requires_ that the suggestion box opens. This is because I am progressingly enhancing the suggestions as the user selects/taps (tap ahead inspired). Unfortunately this now breaks and was doing my head in until I finally found this issue!

To satisfy both our needs, would it be possible to add a further argument to the 'val' call like so:
`.typeahead('val', newValue, [true|false])`
The flag simply tells typeahead whether or not to open the suggestion dropdown. The default can be `false`, i.e. if the last argument is not specified, then don't show the dropdown.

**Comment by austinzuffi** [comment]
this works for me, event is in backbone.js
```
'typeahead:cursorchanged .typeahead'  : function() {
    var typedInput = $('.typeahead').typeahead('val');
    //set suggestion val
    $('.typeahead').val(typedInput);
}
```

**Comment by lddubeau** [comment]
I've run into this issue with typeahead 0.10.5. What my code initially did was to:

1. Focus the typeahead.
2. Use `.typeahead('val', <whatever>);` to set its value.

On all platforms I tested on except IE, it worked fine: the dropdown is shown when the value is set. On IE, the problem is that focus events get delivered asynchronously. So by the time `.typeahead('val', ...)` is executed, the typeahead is not active yet because it is activated only on focus and the focus has not happened yet. So the dropdown is not shown.

I've worked around the problem by using undocumented parts of the plugin. Right after the typeahead is created and focused, I do:

      var tt = $.data(ta, "ttTypeahead");
      tt.isActivated = true;

`ta` is the DOM element for which the `.typeahead(...)` was called to create the typeahead. The code above gets the object of class `Typeahead` that was internally created by the plugin and sets its `isActivated` property to `true`. It is also set to `true` when the input is focused.
